# Generated by Django 6.0.6 on 2026-06-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cateogry',
            new_name='category',
        ),
    ]
